# Copyright (c) 2026 p-darksy-r and Local Network Scanner. Licensed under the MIT License.

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

# Copyright (c) 2026 p-darksy-r and Local Network Scanner. Licensed under the MIT License.
