blank_issues_enabled: false
contact_links:
  - name: Comunicar uma vulnerabilidade
    url: https://github.com/p-darksy-r/LocalNetworkScanner/security/advisories/new
    about: Utilize um Security Advisory privado para vulnerabilidades exploráveis.
